// Generated by tools/generate_game_versions.py; edit game_versions.json.
namespace Fable2Launcher.Constants;
public sealed record GameVersion(string Id, string Hash, string Name, bool Compatible,
    string Reason, int Language, string CodeGroup, string[] RequiredFiles,
    string[] RejectFiles, string[] RejectDirectories);
public static class GameVersions
{
    public const string DefaultProfile = "goty-us-eu";
    public const string CompatibleProfile = "goty-compatible";
    public const string CodeGroup = "goty-identical-payload-2026-09-28";
    public static readonly GameVersion[] All = [
        new("goty-us-eu", "88c4ef2e18e65409444d1b068eff921d1f7e180a5ae64edc64ba6b0872372662", "GOTY USA/Europe", true, "Original GOTY USA/Europe executable and content detected.", 1, "goty-identical-payload-2026-09-28", ["data/gold_version.txt", "data/startup.vfsconfig"], ["data/tu1_data.bnk"], ["data/language/de-de"]),
        new("goty-german", "3f36e7870a06e04b3702760e93c61b1c7fded321b94021da6bfa120b424e6eb4", "German GOTY", true, "Original German GOTY executable and localization detected.", 3, "goty-identical-payload-2026-09-28", ["data/gold_version.txt", "data/startup.vfsconfig", "data/language/de-de/text/book.babel"], ["data/tu1_data.bnk"], ["data/language/de-de"]),
        new("german-retail-tu1", "cec9238ef5d7b391345a8897ef00a4673ae4f106f89385c81723ba5f9d0807b5", "German retail/TU1", false, "German retail/TU1 needs its own validated recompilation profile and is not supported yet.", 3, "unverified", [], [], []),
        new("goty-french", "0e1ea96ded3407874cbbb3a9587d79f1340a57a9d1ba2feebcfdbc9ed1e4b6e5", "GOTY France", true, "Original French GOTY executable and content detected.", 1, "goty-identical-payload-2026-09-28", ["data/gold_version.txt", "data/startup.vfsconfig"], ["data/tu1_data.bnk"], []),
        new("goty-italy", "27a7ad9d66df4131a7fc352829d9df4df40206350ec63c7ee1b53bd71b203da0", "GOTY Italy", true, "Original Italian GOTY executable and content detected.", 1, "goty-identical-payload-2026-09-28", ["data/gold_version.txt", "data/startup.vfsconfig"], ["data/tu1_data.bnk"], []),
        new("japan", "3ca11c7b9b62e4935b42118f6d3d52bc33a7d72b3ced852e46c2236dd627972d", "Japan", false, "Original Japanese needs its own validated recompilation profile and is not supported yet.", 1, "unverified", [], [], []),
        new("goty-russia", "aaf100ce83994d178c6585ab502babfd6b3c9d0739017e96e6e5d61bcbbca943", "GOTY Russia", true, "Original Russian GOTY executable and content detected.", 1, "goty-identical-payload-2026-09-28", ["data/gold_version.txt", "data/startup.vfsconfig"], ["data/tu1_data.bnk"], []),
        new("goty-spain", "6422e22327b576f6d188206ab00112eedc780f3d130a45ca6ac42f7e4b99da6c", "GOTY Spain", true, "Original Spanish GOTY executable and content detected.", 1, "goty-identical-payload-2026-09-28", ["data/gold_version.txt", "data/startup.vfsconfig"], ["data/tu1_data.bnk"], []),
        new("goty-asia", "7a680559a20178b15745c20180a31fa905bbdab3da9f8a146646bb90267364eb", "GOTY Asia", false, "asia requires its own validated recompilation profile and is not supported yet.", 1, "unverified", [], [], []),
        new("goty-latin-america", "7472468f71f31663898dd006b4750c8f07f7947ed0ed1d95d316bd3762cbfb00", "GOTY Latin America", false, "latin-america requires its own validated recompilation profile and is not supported yet.", 1, "unverified", [], [], []),
    ];
}
